local map = require("utils.map")
local M = require("utils.format")

map("n", "<c-o>", "<c-o>zzzv")
map("n", "<c-i>", "<c-i>zzzv")
map("n", "n", "nzzzv")
map("n", "N", "Nzzzv")
map("n", "J", "mzJ`z")
map("n", "<s-l>", "<cmd>tabnext<cr>", { desc = "Next tab" })
map("n", "<s-h>", "<cmd>tabprevious<cr>", { desc = "Previous tab" })
map("t", "<esc>", "<C-\\><C-N>")
map({ "n", "v" }, "<leader>f", M.format, { desc = "Format buffer" })
map({ "n" }, "<leader>l", "<cmd>Lazy<cr>", { desc = "Lazy" })
