# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$os\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:#394260 bg:#212736)\
$character
"""

right_format = """
$status\
$aws\
$nodejs\
$terraform\
$time\
"""

[character]
success_symbol = '[ ](bold green)'
error_symbol = "[ ✗](bold red)"
vimcmd_symbol = "[ ](bold green)"
vimcmd_visual_symbol = "[ ](bold yellow)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[os]
style = "bg:#a3aed2 fg:#090c0c"
disabled = false

[os.symbols]
Macos = "  "
Ubuntu = "  "
Manjaro = " 󱘊 "

[git_branch]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $branch ]($style)'

[git_commit]
style = "fg:#769ff0 bg:#394260"
tag_symbol = "  "
format = '[\($hash$tag\)]($style)'
tag_disabled = false

[git_state]
style = "fg:#769ff0 bg:#394260"
format = '[ \($state( $progress_current/$progress_total)\) ]($style)'

[git_status]
style = "fg:#769ff0 bg:#394260"
format = '[($all_status$ahead_behind)]($style)'

[nodejs]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[status]
symbol = "✗"
format = "[ $symbol $status ]($style)"
style = 'fg:red'
disabled = false

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "fg:#a0a9cb bg:#394260"
format = '[  $time ]($style)'
